Repository marcosdosea/DoeVida, pull requests merged in 2021-11, with the labels that each got.

#84 Davi issue71 adicionar design system create doador
  Codigo/DoeVidaWeb/Controllers/DoadorController.cs
  Codigo/DoeVidaWeb/Views/Doador/Index.cshtml
  Codigo/DoeVidaWeb/Views/Shared/_Layout.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
Labels: implmentation

#86 Idylicaro issue81 manter agendamento
  Codigo/Core/DTO/AgendamentoListDTO.cs
  Codigo/Core/Service/IAgendamentoService.cs
  Codigo/DoeVida.sln
  Codigo/DoeVidaWeb/Controllers/AgendamentoController.cs
  Codigo/DoeVidaWeb/Mappers/AgendamentoListDTOProfile.cs
  Codigo/DoeVidaWeb/Mappers/AgendamentoProfile.cs
  Codigo/DoeVidaWeb/Startup.cs
  Codigo/DoeVidaWeb/ViewModels/AgendamentoDetailsDTOViewModel.cs
  Codigo/DoeVidaWeb/ViewModels/AgendamentoListDTOViewModel.cs
  Codigo/DoeVidaWeb/ViewModels/AgendamentoViewModel.cs
  Codigo/DoeVidaWeb/Views/Agendamento/Create.cshtml
  Codigo/DoeVidaWeb/Views/Agendamento/Edit.cshtml
  Codigo/DoeVidaWeb/Views/Agendamento/Index.cshtml
  Codigo/DoeVidaWeb/Views/Shared/_Layout.cshtml
  Codigo/DoeVidaWeb/mono_crash.21acb2c5e9.0.json
  Codigo/DoeVidaWeb/wwwroot/css/global.css
  Codigo/DoeVidaWebTests/Controllers/AgendamentoControllerTests.cs
  Codigo/DoeVidaWebTests/DoeVidaWebTests.csproj
  Codigo/Service/AgendamentoService.cs
  Codigo/ServiceTests/AgendamentoServiceTests.cs
  Codigo/ServiceTests/ServiceTests.csproj
Labels: implementation

#87 Davi issue#71 adicionar design system create doador
  Codigo/Core/DTO/AgendamentoDetailsDTO.cs
  Codigo/DoeVidaWeb/Controllers/AgendamentoController.cs
  Codigo/DoeVidaWeb/Mappers/AgendamentoDetailsDTOProfile.cs
  Codigo/DoeVidaWeb/ViewModels/DoadorViewModel.cs
  Codigo/DoeVidaWeb/Views/Agendamento/Details.cshtml
  Codigo/DoeVidaWeb/Views/Agendamento/Index.cshtml
  Codigo/DoeVidaWeb/Views/Doador/Create.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
  Codigo/Service/AgendamentoService.cs
Labels: implementation

#88 Idylicaro issue81 manter agendamento
  Codigo/Core/Agendamento.cs
  Codigo/Core/DTO/AgendamentoDetailsDTO.cs
  Codigo/Core/DTO/AgendamentoListDTO.cs
  Codigo/Core/Service/IAgendamentoService.cs
  Codigo/DoeVidaWeb/Controllers/AgendamentoController.cs
  Codigo/DoeVidaWeb/Mappers/AgendamentoDetailsDTOProfile.cs
  Codigo/DoeVidaWeb/Mappers/AgendamentoListDTOProfile.cs
  Codigo/DoeVidaWeb/Mappers/AgendamentoProfile.cs
  Codigo/DoeVidaWeb/ViewModels/AgendamentoDetailsDTOViewModel.cs
  Codigo/DoeVidaWeb/ViewModels/AgendamentoListDTOViewModel.cs
  Codigo/DoeVidaWeb/ViewModels/AgendamentoViewModel.cs
  Codigo/DoeVidaWeb/Views/Agendamento/Index.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
  Codigo/DoeVidaWebTests/Controllers/AgendamentoControllerTests.cs
  Codigo/Service/AgendamentoService.cs
  Codigo/ServiceTests/AgendamentoServiceTests.cs
Labels: enhancement

#90 Foi adicionado testes a Organização Controller e Service
  Codigo/Core/Organizacao.cs
  Codigo/Core/Service/IOrganizacaoService.cs
  Codigo/DoeVidaWeb/Controllers/OrganizacaoController.cs
  Codigo/DoeVidaWeb/Mappers/OrganizacaoProfile.cs
  Codigo/DoeVidaWeb/ViewModels/OrganizacaoViewModel.cs
  Codigo/DoeVidaWebTests/Controllers/OrganizacaoControllerTests.cs
  Codigo/Service/OrganizacaoService.cs
  Codigo/ServiceTests/OrganizacaoServiceTests.cs
Labels: Test

#91 Davi issue71 add design system
  Codigo/DoeVidaWeb/Views/Doador/Create.cshtml
  Codigo/DoeVidaWeb/Views/Doador/Delete.cshtml
  Codigo/DoeVidaWeb/Views/Doador/Details.cshtml
  Codigo/DoeVidaWeb/Views/Doador/Edit.cshtml
  Codigo/DoeVidaWeb/Views/Doador/Index.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
Labels: implementation

#92 Adicionar teste no CUS - Manter Item
  Codigo/DoeVidaWebTests/Controllers/ItemControllerTests.cs
  Codigo/ServiceTests/ItemServiceTests.cs
Labels: implementation

#93 Davi issue89 add teste doador
  Codigo/DoeVidaWebTests/Controllers/DoadorControllerTests.cs
  Codigo/ServiceTests/DoadorServiceTests.cs
Labels: Test

#95 Atualizando artefatos
  Requisitos/documentos de casos de uso/CSU01 - Autenticar Usuario.docx
  Requisitos/documentos de casos de uso/CSU02 - Manter Doador.docx
  Requisitos/documentos de casos de uso/CSU03 - Manter Vagas e Horarios de Doação.docx
  Requisitos/documentos de casos de uso/CSU04 - Manter Itens Apoio a Doação.docx
  Requisitos/documentos de casos de uso/CSU05 - Manter Organização Receptora de Doação.docx
  Requisitos/documentos de casos de uso/CSU06 - Agendar doação.docx
  Requisitos/documentos de casos de uso/CSU07 - Recolher Doação.docx
  Requisitos/documentos de casos de uso/CSU08 - Entregar Item Apoio a Doação.docx
  Requisitos/documentos de casos de uso/CSU09 - Manter Servidor.docx
  Requisitos/documentos de casos de uso/CSU10 - Manter Agendamentos.docx
  Requisitos/documentos de casos de uso/CSU11 - Manter Solicitação.docx
  Requisitos/documentos de casos de uso/CSU12 - Solicitar Item.docx
  Requisitos/documentos de casos de uso/DD-DoeVida.docx
Labels: documentation

#99 Foi resolvido o problema na paginação
  Codigo/DoeVidaWeb/Views/Agendamento/Index.cshtml
  Codigo/Service/AgendamentoService.cs
Labels: fix

#100 Idylicaro issue97 pagination
  Codigo/Core/Service/IOrganizacaoService.cs
  Codigo/DoeVidaWeb/Controllers/OrganizacaoController.cs
  Codigo/DoeVidaWeb/Views/Organizacao/Index.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
  Codigo/DoeVidaWebTests/Controllers/OrganizacaoControllerTests.cs
  Codigo/Service/OrganizacaoService.cs
  Codigo/ServiceTests/OrganizacaoServiceTests.cs
Labels: implementation

#102 Victor issue#95 implementar dto item
  Codigo/Core/DTO/ItemListDTO.cs
  Codigo/Core/Service/IItemService.cs
  Codigo/DoeVidaWeb/Controllers/ItemController.cs
  Codigo/DoeVidaWeb/Mappers/ItemListDTOProfile.cs
  Codigo/DoeVidaWeb/ViewModels/ItemListDTOViewModel.cs
  Codigo/DoeVidaWeb/Views/Item/Details.cshtml
  Codigo/DoeVidaWeb/Views/Item/Index.cshtml
  Codigo/Service/AgendamentoService.cs
  Codigo/Service/ItemService.cs
Labels: implementation

#104 Foi alterado para o padrão da aplicação
  Codigo/DoeVidaWeb/Views/Agendamento/Index.cshtml
Labels: implementation

#107 Idyicaro issue94
  Analise Projeto/DoeVida_Dump.sql
  Codigo/Core/DoeVidaDbContext.cs
  Codigo/Core/Pessoa.cs
  Codigo/DoeVidaWeb/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/DoeVidaWeb/Controllers/DoadorController.cs
  Codigo/DoeVidaWeb/DoeVidaWeb.csproj
  Codigo/DoeVidaWeb/Mappers/DoadorProfile.cs
  Codigo/DoeVidaWeb/Startup.cs
  Codigo/DoeVidaWeb/ViewModels/DoadorViewModel.cs
  Codigo/DoeVidaWeb/Views/Doador/Create.cshtml
  Codigo/DoeVidaWeb/Views/Doador/Register.cshtml
  Codigo/DoeVidaWeb/Views/Shared/_BlankLayout.cshtml
  Codigo/DoeVidaWeb/Views/Shared/_LoginPartial.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
  Codigo/DoeVidaWeb/wwwroot/js/site.js
  Codigo/DoeVidaWebTests/Controllers/DoadorControllerTests.cs
Labels: implementation

#109 Davi issue108 design system login
  Codigo/DoeVidaWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/DoeVidaWeb/Views/Shared/_Layout.cshtml
  Codigo/DoeVidaWeb/wwwroot/assets/logo.png
  Codigo/DoeVidaWeb/wwwroot/assets/logo.svg
  Codigo/DoeVidaWeb/wwwroot/assets/memphis.png
  Codigo/DoeVidaWeb/wwwroot/css/login.css
Labels: implementation

#110 Refatoração no metódo de paginação
  Codigo/Core/Service/IAgendamentoService.cs
  Codigo/Core/Service/IOrganizacaoService.cs
  Codigo/DoeVidaWeb/Controllers/AgendamentoController.cs
  Codigo/DoeVidaWebTests/Controllers/AgendamentoControllerTests.cs
  Codigo/DoeVidaWebTests/Controllers/ItemControllerTests.cs
  Codigo/Service/AgendamentoService.cs
  Codigo/Service/OrganizacaoService.cs
  Codigo/ServiceTests/OrganizacaoServiceTests.cs
Labels: implementation
