Repository marcosdosea/DoeVida, pull requests merged in 2021-12, with the labels that each got.

#112 issue#111 - Adicionada Paginacao Manter Item
  Codigo/Core/Service/IItemService.cs
  Codigo/DoeVidaWeb/Controllers/ItemController.cs
  Codigo/DoeVidaWeb/Views/Item/Index.cshtml
  Codigo/Service/ItemService.cs
Labels: implementation

#114 Foi corrigido o pequeno erro na URL do left button
  Codigo/DoeVidaWeb/Controllers/OrganizacaoController.cs
  Codigo/DoeVidaWeb/Views/Agendamento/Index.cshtml
  Codigo/DoeVidaWeb/Views/Item/Index.cshtml
  Codigo/DoeVidaWeb/Views/Organizacao/Index.cshtml
Labels: wontfix

#125 Correção de campo cep
  Codigo/DoeVidaWeb/Views/Doador/Create.cshtml
  Codigo/DoeVidaWeb/wwwroot/css/global.css
Labels: bug

#126 Davi aythorization doador
  Codigo/DoeVidaWeb/Controllers/DoadorController.cs
  Codigo/DoeVidaWeb/Controllers/HomeController.cs
  Codigo/DoeVidaWeb/Views/Shared/_Layout.cshtml
  Codigo/DoeVidaWeb/Views/Shared/_LoginPartial.cshtml
Labels: implementation

#129 Adicionando Auth no controller Agendamento
  Codigo/DoeVidaWeb/Controllers/AgendamentoController.cs
Labels: implementation

#132 Adicionando Autorizacao no item controller
  Codigo/DoeVidaWeb/Controllers/ItemController.cs
Labels: implementation
